from abc import ABC, abstractmethod
from typing import Optional, List
from src.domain.models.auction_session import AuctionSession

class IAuctionSessionRepository(ABC):
    @abstractmethod
    def get(self, auction_id:int) -> Optional[AuctionSession]: ...
    @abstractmethod
    def list(self, page:int=1, limit:int=20) -> List[AuctionSession]: ...
    @abstractmethod
    def create(self, auction:AuctionSession) -> AuctionSession: ...
    @abstractmethod
    def update(self, auction:AuctionSession) -> AuctionSession: ...
    @abstractmethod
    def delete(self, auction_id:int) -> None: ...
