from abc import ABC, abstractmethod
from typing import Optional, List
from src.domain.models.auction_item import AuctionItem

class IAuctionItemRepository(ABC):
    @abstractmethod
    def get(self, item_id:int) -> Optional[AuctionItem]: ...
    @abstractmethod
    def list(self, page:int=1, limit:int=20) -> List[AuctionItem]: ...
    @abstractmethod
    def create(self, item:AuctionItem) -> AuctionItem: ...
    @abstractmethod
    def update(self, item:AuctionItem) -> AuctionItem: ...
    @abstractmethod
    def delete(self, item_id:int) -> None: ...
